# Generated by Django 3.0.5 on 2020-08-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Sulton_links',
        ),
    ]
