# Generated by Django 3.0.5 on 2020-07-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co_Principal_Investigators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('bio', models.TextField()),
                ('image', models.FilePathField()),
            ],
        ),
    ]
