# Generated by Django 3.0.5 on 2020-07-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_auto_20200715_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory_comitee',
            name='profession',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='co_investigators',
            name='profession',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='co_principal_investigators',
            name='profession',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project_personnel',
            name='profession',
            field=models.TextField(default=''),
        ),
    ]
