# Generated by Django 3.0.5 on 2020-08-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0004_auto_20200716_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory_comitee',
            name='place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='co_investigators',
            name='place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='co_principal_investigators',
            name='place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project_personnel',
            name='place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
