# Generated by Django 3.0.5 on 2020-09-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_auto_20200807_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_personnel',
            name='view',
            field=models.BooleanField(default=True),
        ),
    ]
