# Generated by Django 3.0.6 on 2020-06-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20200619_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
        migrations.RemoveField(
            model_name='resource_page',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='pdf_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
