# Generated by Django 3.0.5 on 2020-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_auto_20200711_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_date', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Publications',
            },
        ),
    ]
