# Generated by Django 3.0.5 on 2020-09-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_auto_20200723_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_page',
            name='link',
            field=models.TextField(),
        ),
    ]
