# Generated by Django 3.0.5 on 2020-09-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_auto_20200913_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.BooleanField(default=False),
        ),
    ]
