# Generated by Django 3.0.5 on 2020-09-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
