# Generated by Django 3.1.3 on 2020-11-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_post_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='related_projects',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
