# Generated by Django 3.1.3 on 2020-12-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_auto_20201207_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_presentation_link',
            field=models.BooleanField(default=False),
        ),
    ]
