# Generated by Django 3.0.5 on 2021-06-30 03:25

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_post_show_presentation_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStories',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('presentation_link', models.TextField(blank=True)),
                ('show_presentation_link', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('view', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Patient Storie',
            },
        ),
    ]
