# Generated by Django 3.0.5 on 2021-07-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_patientstories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aim1',
        ),
        migrations.AlterModelOptions(
            name='patientstories',
            options={'verbose_name': 'Patient Stories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Case Studies'},
        ),
    ]
