# Generated by Django 3.0.5 on 2021-07-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_auto_20210718_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstories',
            name='picture',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
