# Generated by Django 3.0.5 on 2021-07-19 02:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0028_auto_20210718_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstories',
            name='picture',
            field=models.ImageField(default='none', storage=django.core.files.storage.FileSystemStorage(location='/static/'), upload_to=''),
        ),
    ]
