# Generated by Django 3.0.5 on 2021-07-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0032_auto_20210718_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstories',
            name='article_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
